version: '3.1'
services:
  nexus3:
    pull_policy: always
    expose:
      - 127.0.0.1:8081:8081
    volumes:
      - nexus-data:/nexus-data
    image: "registry.pupgizmo.com/library/nexus3:3.61.0"
  minio:
    expose:
      - 9000:9000
      - 9001:9001
    volumes: 
      - minio-data:/minio
    command: server /minio --console-address ":9001"
    image: minio/minio
volumes:
  nexus-data:
  minio-data:

